---
title: "CaHASE2 Anthropometry and Biomarkers Plots"
author: "R.Welch"
date: "2025-06-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Working notes:
- apply same time frames as for CaHASE2 (Nov22-23, Nov23-24, Nov24-Feb25)

libraries
```{r : reading libraries, include= FALSE}
packages <- c("tidyverse", "readxl", "dplyr", "magrittr", "mixtools", "emmeans", "readr","data.table", "lubridate", "ggplot2", "skimr", "ggstatsplot","summarytools", "knitr", "here", "ggthemes", "Amelia", "tidyr", "naniar", "stringr", "janitor", "ggbreak", "patchwork", "plotrix", "viridis", "hrbrthemes", "showtext")

lapply(packages, library, character.only = TRUE)
```

```{r : set up #2}
# read in data
all_data <- read.csv("Outputs/Dataframe outputs/CaHASE2/all_data_Nov22_Feb25.csv", header=T, na.strings= c("", "NA"))

# colours
myColours <- c("purple", "lightblue", "grey")

# add font
font_add(family = "Arial", regular = "Arial.ttf")

all_data$Centre.ID.x <- as.factor(all_data$Centre.ID.x)
```


```{r : anthro plots}
# height
height_all <- MDBoxPlot(all_data, "HeightSDSforBA", "SBS", "Height SDS for BA")+
  scale_y_continuous(breaks = seq(-6, 6, by = 2))
 
weight_all <- MDBoxPlot(all_data, "WeightSDS", "SBS", "Weight SDS") +
  ylim(-5, 7)

BMI <- MDBoxPlot(all_data, "BMISDS", "None", "BMI SDS") +
  ylim(-5,7.5)

age <- MDBoxPlot(all_data, "Age", "None", "Age")
```

```{r : violin plots}
BMI_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = BMISDS, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ylim(-5, 7.5) +
  ggtitle("BMISDS 22-25") +
  geom_point(position = position_jitter(seed = 1, width = 0.2))

# Age_violin <- ggplot(all_data_22_25, aes(x = Sex.at.birth.x, y = Age, fill = Sex.at.birth.x)) +
#   geom_violin() +
#   theme_classic() +
#   scale_y_continuous(breaks = seq(0, 90, by = 5)) +
#   ggtitle("Age 22-25") +
#   geom_point(position = position_jitter(seed = 1, width = 0.2))

Weight_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = WeightSDS, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ylim(-5,7) +
  ggtitle("WeightSDS 22-25") +
  geom_point(position = position_jitter(seed = 1, width = 0.2))

Height_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = HeightSDS, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ylim(-5,5) +
  ggtitle("HeightSDS 22-25") +
  geom_point(position = position_jitter(seed = 1, width = 0.2))

# BP_systolic_violin <- ggplot(all_data_22_25, aes(x = Sex.at.birth.x, y = Systolic.Blood.Pressure, fill = Sex.at.birth.x)) +
#   geom_violin() +
#   theme_classic() +
#   scale_y_continuous(breaks = seq(80, 180, by = 10)) +
#   ggtitle("Systolic blood pressure (mmHg) 22-25") +
#   geom_point(position = position_jitter(seed = 1, width = 0.2))
# 
# BP_diastolic_violin <- ggplot(all_data_22_25, aes(x = Sex.at.birth.x, y = Diastolic.Blood.Pressure, fill = Sex.at.birth.x)) +
#   geom_violin() +
#   theme_classic() +
#   scale_y_continuous(breaks = seq(45, 110, by = 10)) +
#   ggtitle("Diastolic blood pressure (mmHg) 22-25")  +
#   geom_point(position = position_jitter(seed = 1, width = 0.2))

OHP_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = `X17.OHP.value`, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ggtitle("17OHP concentrations 22-25") +
  geom_point(position = position_jitter(seed = 1, width = 0.2)) +
  scale_y_continuous(trans = "log10") +
  geom_hline(yintercept = 30, colour = "red") +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=36, alpha=.5, fill='grey')

andro_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = Androstenedione.value, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Androstenedione concentrations") +
  geom_point(position = position_jitter(seed = 1, width = 0.2)) +
  scale_y_break(c(10,30,55,70), scale = 0.25) +
  scale_y_continuous(breaks = seq(0, 70, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")

testosterone_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Testosterone concentrations") +
  geom_point(position = position_jitter(seed = 1, width = 0.2)) +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5))

# add in age category grouping
testosterone_violin2 <- ggplot(all_data, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Age.category)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Testosterone concentrations 22-25") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
  scale_fill_manual(values = myColours) +
  geom_point(position = position_dodge(width = 1),
                 aes(group = Age.category)) 


# introduce age category
# only need age category for males so will need to do some powerpoint cropping
    testosterone_all_violin_2 <- ggplot(all_data, aes(x = Sex.at.birth, y = Total.testosterone.value, fill = Age.category, col = Sex.at.birth)) +
      geom_violin() +
      scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
      labs(title = "Testosterone 22-25", x = "Centre ID", y = "Total.testosterone.value") +
      theme_classic() +
      theme() +
      scale_fill_manual(values = myColours) +
      geom_point(position = position_dodge(width = 0.75),
                 aes(group = Age.category))
#

renin_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = Renin.plasma.activity, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Renin plasma activity") +
  geom_point(position = position_jitter(seed = 1, width = 0.2)) +
  scale_y_break(c(55, 100), scale = 0.25)

```

```{r : biomarker plots}
# have played around with various axis breaks and y scales to get data to look as clear as possible...
## testosterone
testosterone_all <- MDBoxPlot(all_data, "Total.testosterone.value", "Sex only", "Testosterone 22-25") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5))

# introduce age category
# only need age category for males so will need to do some powerpoint cropping
    testosterone_all2 <- ggplot(all_data, aes(x = Sex.at.birth, y = Total.testosterone.value, fill = Age.category, col = Sex.at.birth)) +
      geom_boxplot(position = position_dodge2(preserve='single'),) +
      scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
      labs(title = "Testosterone 22-25", x = "Centre ID", y = "Total.testosterone.value") +
      theme_classic() +
      theme() +
      scale_fill_manual(values = myColours) +
      geom_point(position = position_dodge(width = 0.75),
                 aes(group = Age.category))
#

## renin plasma activity
renin_all <- MDBoxPlot(all_data, "Renin.plasma.activity", "SBS", "Renin plasma activiy") +
scale_y_break(c(40, 100), scale = 0.25)

## 17OHP
OHP_all <- MDBoxPlot(all_data, "X17.OHP.value", "NTEO", "17 OHP values 22-25") +
  scale_y_continuous(trans = "log10")  +
  geom_hline(yintercept = 30, colour = "red") +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=36, alpha=.5, fill='grey')

##andro
andro_all <- MDBoxPlot(all_data, "Androstenedione.value", "NTEO", "Andro values") +
  scale_y_break(c(20, 74), scale = 0.1) + 
  scale_y_continuous(breaks = seq(0, 75, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")
```

```{r}

```

```{r : end of script message}
print("Script complete")
```









