---
title: "medicationDataAndPlots"
author: "R.Welch"
date: "2025-16-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r : reading libraries, include= FALSE}
packages <- c("tidyverse", "readxl", "dplyr", "magrittr", "mixtools", "emmeans", "readr","data.table", "lubridate", "ggplot2", "skimr", "ggstatsplot","summarytools", "knitr", "here", "ggthemes", "Amelia", "tidyr", "naniar", "stringr", "janitor", "ggbreak", "patchwork", "plotrix", "viridis", "hrbrthemes", "showtext", "plot3D", "psych")

lapply(packages, library, character.only = TRUE)
```

```{r : set up #2}
# read in data
all_data <- read.csv("Outputs/Dataframe outputs/April 24 Extract (for Irina)/all_data_ICAH_children_2025.csv", header=T, na.strings= c("", "NA"))

# colours
myColours <- c("purple", "lightblue", "grey", "yellow", "red")

# histogram colours
histColours <- c("red", "springgreen2", "royalblue2")
```

```{r : split therapy types}
# remove entries with no medication data
all_data$Centre.ID.x <- as.factor(all_data$Centre.ID.x)
all_data <- all_data[!is.na(all_data$Medicine_1),]
single_therapy <- all_data[all_data$therapy.type == "single",]
combined_therapy <- all_data[all_data$therapy.type == "combined",]
```

```{r : basic stats to check for anomalous values in medications}
# let's do basic stats to see if there are any obvious outliers (this is also done in cleaning script, but repeated here to double check)
# done separately for single_therapy frame
checkdailymedstats <- all_data %>%
  group_by(Medicine_1) %>%
  summarise(mean_standardised_dose = mean(total_daily_HCeq_dose, na.rm = TRUE),
            median_standardised_dose = median(total_daily_HCeq_dose, na.rm = TRUE),
            sd_standardised_dose = sd(total_daily_HCeq_dose, na.rm = TRUE),
            min_standardised_dose = min(total_daily_HCeq_dose, na.rm = TRUE),
            max_standardised_dose = max(total_daily_HCeq_dose, na.rm = TRUE)) %>%
  mutate_if(is.numeric, ~round(., 2))

# if there are any anonymously high values here, double check raw data!
```

```{r : med box plots HC equivalent}
# using MDBoxPlot function
HCe_total_daily_doses <- MDBoxPlot(all_data, "total_daily_HCeq_dose", "None", "HC total daily dose")

HCe_total_violin <- ggplot(all_data, aes(x = Centre.ID.x, y = total_daily_HCeq_dose, fill = Centre.ID.x)) +  geom_violin() +
  theme_classic() +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11,   colour = "red") +
  stat_summary(fun = "mean",
               geom = "point",
               color = "black")

HCe_total_daily_doses_per_BSA <- MDBoxPlot(all_data, "HCe.total.daily.dose.per.BSA", "Sex only", "Total daily HCe / m2")

HCe_total_daily_doses_per_BSA_violin <- ggplot(all_data, aes(x = Centre.ID.x, y = HCe.total.daily.dose.per.BSA, fill = Centre.ID.x)) + geom_violin() +
  theme_classic() +
  stat_summary(fun = "mean",
               geom = "point",
               color = "black")
```

```{r : med box plots dose per BSA values}
# # using MDBoxPlot function

# Hydrocortisone
HC_equiv_BSA_HydrocortisoneBoxPlot_all <- MDBoxPlot(all_data[all_data$Medicine_1 == "Hydrocortisone",], "HCe.total.daily.dose.per.BSA", "None", "HCe per BSA total daily dose HC (all data)") + ylim(0,25) +   annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")

## Prednisolone
HC_equiv_BSA_PrednisoloneBoxPlot_all <- MDBoxPlot(all_data[all_data$Medicine_1 == "Prednisolone",], "HCe.total.daily.dose.per.BSA", "None", "HCe per BSA total daily dose prednisolone (all data)")  +   annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")

# Hydrocortisone
HC_equiv_BSA_EfmodyBoxPlot_all <- MDBoxPlot(all_data[all_data$Medicine_1 == "Efmody",], "HCe.total.daily.dose.per.BSA", "None", "HCe per BSA total daily dose Efmody (all data)") + ylim(0,25) +   annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")
```

```{r : Hce total daily dose per BSA per medication}
HCe_per_BSA_daily_per_medication <-
  ggplot(single_therapy, aes(x = Medicine_1, y = HCe.total.daily.dose.per.BSA, fill = Medicine_1)) +
  geom_violin() +
  labs(title = "HCe total daily dose per BSA per medication", x = "Medicine", y = "HCe total daily dose (mg) mg/m2 per day") +
  theme_classic() +
  theme() +
  geom_point(position = position_dodge(width = 0.75), aes(group = Medicine_1)) +
  scale_y_continuous(breaks = seq(0, 60, by = 2.5)) +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') +
  geom_hline(yintercept = 11, colour = "red")
```

```{r : dose time histograms}
# # using medTimePlot function
timings_long_set_up <- all_data %>%
    pivot_longer(cols = c(Time_1,
                          Time_2,
                          Time_3,
                          Time_4,
                          Time_5),
                 names_to = c("dose_number"),
                 values_to = "time")
  
timings_long <- timings_long_set_up[, c("Centre.ID.x", "dose_number", "time", "Medicine_1", "Medicine_2", "Medicine_3", "Medicine_4", "Medicine_5")]
remove(timings_long_set_up)

dose_timings <- ggplot(timings_long, aes(x = time, fill = dose_number)) +
  geom_histogram(color = "black") +
  scale_fill_manual(values = c("indianred1", "orange1", "yellow2", "palegreen2", "dodgerblue2")) +
  theme_minimal() +
  facet_wrap(~Centre.ID.x, scales = "free_y")
```

```{r : therapy dose trends with facet wrap - HC equivalent total daily doses}
Hce_total_daily_per_med <- ggplot(single_therapy, aes(x = Centre.ID.x, y = total_daily_HCeq_dose, fill = Medicine_1)) +
  geom_boxplot() +
  ggtitle("HCe total daily doses per medication (all data)") +
  facet_wrap(~ Medicine_1, axes = "all", axis.labels = "all") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75))

Hce_per_BSA_total_daily_per_med <- ggplot(single_therapy, aes(x = Centre.ID.x, y = HCe.total.daily.dose.per.BSA, fill = Medicine_1)) +
  geom_boxplot() +
  ggtitle("HCe per BSA total daily doses per medication (all data)") +
  facet_wrap(~ Medicine_1, axes = "all", axis.labels = "all") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75)) +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') +
  geom_hline(yintercept = 11, colour = "red")
```

```{r : HC equiv per BSA doses}
perBSA_therapy_dose_trends_all <- ggplot(single_therapy, aes(x = Centre.ID.x, y = HCe.total.daily.dose.per.BSA, fill = Medicine_1)) +
  geom_boxplot() +
  ggtitle("HC equivalent total daily dose per BSA (all data)") +
  facet_wrap(~ Medicine_1, axes = "all", axis.labels = "all") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75)) +
  theme(axis.text.x = element_text(angle=90)) +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")

perBSA_therapy_dose_trends_all2 <- ggplot(single_therapy, aes(x = Centre.ID.x, y = HCe.total.daily.dose.per.BSA)) +
  geom_boxplot() +
  ggtitle("HC equivalent total daily dose per BSA (all data)") +
  scale_y_continuous(breaks = seq(0, 35, by = 2.5)) +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0), aes(shape = Medicine_1, color = Medicine_1)) +
  scale_shape_manual(values=c(4, 19, 15, 17)) +
  scale_color_manual(values = c("red", "dodgerblue", "gold", "green3")) +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")

perBSA_therapy_dose_trends_all3 <- ggplot(single_therapy, aes(x = Centre.ID.x, y = HCe.total.daily.dose.per.BSA)) +
  geom_violin() +
  ggtitle("HC equivalent total daily dose per BSA (all data)") +
  scale_y_continuous(breaks = seq(0, 35, by = 2.5)) +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0), aes(shape = Medicine_1, color = Medicine_1)) +
  scale_shape_manual(values=c(4, 19, 15, 17)) +
  scale_color_manual(values = c("red", "dodgerblue", "gold", "green3")) +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")
#

# zoom_perBSA_therapy_dose_trends_all_2 <- perBSA_therapy_dose_trends_all_2 + coord_cartesian(ylim = c(0,20))
```

```{r : script completion message}
print("Script complete")
```