---
title: "Anthropometry_and_Biomarkers_Plots"
author: "R.Welch"
date: "2025-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Working notes:
- apply time frames based on tranche dates
1st collection: 2022-09-30
2nd collection: 2024-03-31
3rd collection: 2025-04-07

libraries
```{r : reading libraries, include= FALSE}
packages <- c("tidyverse", "readxl", "dplyr", "magrittr", "mixtools", "emmeans", "readr","data.table", "lubridate", "ggplot2", "skimr", "ggstatsplot","summarytools", "knitr", "here", "ggthemes", "Amelia", "tidyr", "naniar", "stringr", "janitor", "ggbreak", "patchwork", "plotrix", "viridis", "hrbrthemes", "showtext", "plot3D", "plot3Drgl", "GGally", "htmlwidgets", "plotly")

lapply(packages, library, character.only = TRUE)
```

```{r : set up #2}
# read in data
all_data <- read.csv("Outputs/Dataframe outputs/April 24 Extract (for Irina)/all_data_ICAH_children_2025.csv", header=T, na.strings= c("", "NA"))

# colours
myColours <- c("purple", "lightblue", "grey")

# add font
font_add(family = "Arial", regular = "Arial.ttf")

all_data$Centre.ID.x <- as.factor(all_data$Centre.ID.x)

all_data$Date.of.Assessment <- as.Date(all_data$Date.of.Assessment, format = "%Y-%m-%d")

# make time frames based on tranche dates
before_2022 <- all_data %>%
  filter(Date.of.Assessment <= "2022-09-30")

first_to_second <- all_data %>%
  filter(Date.of.Assessment > "2022-09-30" & Date.of.Assessment <= "2024-03-31")

second_to_third <- all_data %>%
  filter(Date.of.Assessment > "2024-03-31")


# add column to 'all_data' to show which time frame each record is (to use for colour grouping in plots later on)
all_data$timeframe[all_data$Date.of.Assessment <= "2022-09-30"] <- "before first collection"
all_data$timeframe[all_data$Date.of.Assessment > "2022-09-30" & all_data$Date.of.Assessment <= "2024-03-31"] <- "2022-2024"
all_data$timeframe[all_data$Date.of.Assessment > "2024-03-21"] <- "2024-2025"
```

```{r : violin plot - height SDS for BA}
heightforBA <- Violin(all_data, "HeightSDSforBA", "None", "HeightSDS for Bone age (all data)")

heightforBA_before_first_collection <- Violin(before_2022, "HeightSDSforBA", "None", "HeightSDS for Bone age (before first collection)")

heightforBA_2022_2024 <- Violin(first_to_second, "HeightSDSforBA", "None", "HeightSDS for Bone age (2022-2024)")

heightforBA_2024_2025 <- Violin(second_to_third, "HeightSDSforBA", "None", "HeightSDS for Bone age (2024-2025)")
```

```{r : violin plot - height SDS for chronological age}
heightforCA <- Violin(all_data, "HeightSDS", "HeightSDS for chronological age (all data)", -4) + ylim(-5,5)

heightforCA_before_first_collection <- Violin(before_2022, "HeightSDS", "HeightSDS for chronological age (before first collection)", -4) + ylim(-5,5)

heightforCA_2022_2024 <- Violin(first_to_second, "HeightSDS", "HeightSDS for chronological age (2022-2024)", -4) + ylim(-5,5)

heightforCA_2024_2025 <- Violin(second_to_third, "HeightSDS", "HeightSDS for chronological age (2024-2025)", -4) + ylim(-5,5)
```

```{r : violin plot - weight SDS}
weight_all <- Violin(all_data, "WeightSDS", "WeightSDS (all data)", -4) + ylim(-5,7.5)

weight_before_first_collection <- Violin(before_2022, "WeightSDS", "WeightSDS (before first collection)", -4) + ylim(-5,7.5)

weight_2022_2024 <- Violin(first_to_second, "WeightSDS", "WeightSDS (2022-2024)", -4) + ylim(-5,7.5)

weight_2024_2025 <- Violin(second_to_third, "WeightSDS", "WeightSDS (2024-2025)", -4) + ylim(-5,7.5)
```

```{r : violin plot - BMI SDS}
BMI_all <- Violin(all_data, "BMISDS", "BMI SDS (all data)", -4) + ylim(-5, 7.5)

BMI_before_first_collection <- Violin(before_2022, "BMISDS", "BMI SDS (before first collection)", -4) + ylim(-5,7.5)

BMI_2022_2024 <- Violin(first_to_second, "BMISDS", "BMI SDS (2022-2024)", -4) + ylim(-5,7.5)

BMI_2024_2025 <- Violin(second_to_third, "BMISDS", "BMI SDS (2024-2025)", -4) + ylim(-5,7.5)


# BMI SDS for patients with low androgen levels - ie.: patients with 17-OHP interpretation of 'low'
# first make dataframes
BMI_low_OHP_all <- all_data[!is.na(all_data$X17.OHP.interpretation),]

BMI_low_OHP_df_before_first_collection <- before_2022[!is.na(before_2022$X17.OHP.interpretation),]
BMI_low_OHP_df_before_first_collection<-BMI_low_OHP_df_before_first_collection[BMI_low_OHP_df_before_first_collection$X17.OHP.interpretation == "Low",]

BMI_low_OHP_df_2022_2024 <- first_to_second[!is.na(first_to_second$X17.OHP.interpretation),]
BMI_low_OHP_df_2022_2024 <- BMI_low_OHP_df_2022_2024[BMI_low_OHP_df_2022_2024$X17.OHP.interpretation == "Low",]

BMI_low_OHP_df_2024_2025 <- second_to_third[!is.na(second_to_third$X17.OHP.interpretation),]
BMI_low_OHP_df_2024_2025 <- BMI_low_OHP_df_2024_2025[BMI_low_OHP_df_2024_2025$X17.OHP.interpretation == "Low",]

BMI_all_low_OHP <- Violin(BMI_low_OHP_all, "BMISDS", "BMI SDS with low androgen (all data)", -4) + ylim(-5, 7.5)

BMI_low_OHP_before_first_collection <- Violin(BMI_low_OHP_df_before_first_collection, "BMISDS", "BMI SDS with low androgen (before first collection)", -4) + ylim(-5,7.5)

BMI_low_OHP_2022_2024 <- Violin(BMI_low_OHP_df_2022_2024, "BMISDS", "BMI SDS with low androgen (2022-2024)", -4) + ylim(-5,7.5)

BMI_low_OHP_2024_2025 <- Violin(BMI_low_OHP_df_2024_2025, "BMISDS", "BMI SDS with low androgen (2024-2025)", -4) + ylim(-5,7.5)

#
BMI_test <- ggplot(all_data, aes(x = Sex.at.birth, y = BMISDS)) +
  geom_boxplot() +
  ggtitle("BMI SDS (all data)") +
  ylim(-5, 7.5) +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0), aes(shape = timeframe, color = timeframe)) +
  scale_shape_manual(values=c(19, 19, 19)) +
  scale_color_manual(values = c("green", "dodgerblue", "red")) +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")
#
```

```{r : violin plot - 17-OHP}
OHP_all <- Violin(all_data, "X17.OHP.value", "17-OHP concentrations (all data)", 0.05) + scale_y_continuous(trans = "log10") +
  geom_hline(yintercept = 30, colour = "red") +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=36, alpha=.5, fill='grey')

OHP_before_first_collection <- Violin(before_2022, "X17.OHP.value", "17-OHP concentrations (before 2022)", 0.05) + scale_y_continuous(trans = "log10") +
  geom_hline(yintercept = 30, colour = "red") +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=36, alpha=.5, fill='grey')

OHP_2022_2024 <- Violin(first_to_second, "X17.OHP.value", "17-OHP concentrations (2022-2024)", 0.05) + scale_y_continuous(trans = "log10") +
  geom_hline(yintercept = 30, colour = "red") +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=36, alpha=.5, fill='grey')

OHP_2024_2025 <- Violin(second_to_third, "X17.OHP.value", "17-OHP concentrations (2024-2025)", 0.05) + scale_y_continuous(trans = "log10") +
  geom_hline(yintercept = 30, colour = "red") +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=36, alpha=.5, fill='grey')
```

```{r : violin plot - renin plasma activity}
renin_all <- Violin(all_data, "Renin.plasma.activity", "Renin plasma activity (all data)", 45) +
  scale_y_break(c(60,100), scale = 0.25)

renin_before_first_collection <- Violin(before_2022, "Renin.plasma.activity", "Renin plasma activity (before 2022)", 50) +
  scale_y_break(c(60,100), scale = 0.25)

renin_2022_2024 <- Violin(first_to_second, "Renin.plasma.activity", "Renin plasma activity (2022-2024)", 50)

renin_2024_2025 <- Violin(second_to_third, "Renin.plasma.activity", "Renin plasma activity (2024-2025)", 50) +
  scale_y_break(c(100, 400), scale = 0.25)
```

```{r : violin plot - testosterone}
# need to split into age groupings for males (<12 years old and >)
# can't work out how to streamline this bit, so I have got two plots per timeframe - one without age categories (to use for female and NA) and one with age categories (to use for males)
# will need to do powerpoint manipulation to get final plots
# only males need to be split by age category

testo_all <- Violin(all_data, "Total.testosterone.value", "Total testosterone (all data)", 10)

testosterone_all_2 <- ggplot(all_data, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Age.category)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Total testosterone (all data)") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
  scale_fill_manual(values = myColours) +
  geom_point(position = position_dodge(width = 1),
                 aes(group = Age.category))

testo_before_first_collection <- Violin(before_2022, "Total.testosterone.value", "Total testosterone (before 2022)", 10)

testosterone_before_first_collection_2 <- ggplot(before_2022, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Age.category)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Total testosterone (before 2022)") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
  scale_fill_manual(values = myColours) +
  geom_point(position = position_dodge(width = 1),
                 aes(group = Age.category))

testo_2022_2024 <- Violin(first_to_second, "Total.testosterone.value", "Total testosterone (2022-2024)", 10)

testosterone_2022_2024_2 <- ggplot(first_to_second, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Age.category)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Total testosterone (2022-2024)") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
  scale_fill_manual(values = myColours) +
  geom_point(position = position_dodge(width = 1),
                 aes(group = Age.category))

testo_2024_2025 <- Violin(second_to_third, "Total.testosterone.value", "Total testosterone (2024-2025)", 10)

testosterone_2024_2025_2 <- ggplot(second_to_third, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Age.category)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Total testosterone (2024-2025)") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
  scale_fill_manual(values = myColours) +
  geom_point(position = position_dodge(width = 1),
                 aes(group = Age.category))
```

  geom_point(position = position_dodge(width = 1),
                 aes(group = Age.category))
                 

```{r : violin plot - androstenedione}
andro_all <- Violin(all_data, "Androstenedione.value", "Androstenedione concentrations (all data)", 20) +
  scale_y_break(c(20,30,55,70), scale = 0.25) +
  scale_y_continuous(breaks = seq(0, 70, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")

andro_before_first_collection <- Violin(before_2022, "Androstenedione.value", "Androstenedione concentrations (before 2022)", 20) +
  scale_y_break(c(20,30,55,70), scale = 0.25) +
  scale_y_continuous(breaks = seq(0, 70, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")

andro_2022_2024 <- Violin(first_to_second, "Androstenedione.value", "Androstenedione concentrations (2022-2024))", 20) +
  scale_y_break(c(28,35), scale = 0.25) +
  scale_y_continuous(breaks = seq(0, 70, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")

andro_2024_2025 <- Violin(second_to_third, "Androstenedione.value", "Androstenedione concentrations (2024-2025)", 20) +
  scale_y_continuous(breaks = seq(0, 70, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")
```

```{r : 3D plots - biomarkers vs GC dose}
data_biomarkers <- select(all_data, c("Sex.at.birth", "X17.OHP.value", "Androstenedione.value", "Renin.value", "Total.testosterone.value", "HCe.total.daily.dose.per.BSA"))

# check here for anomalously high biomarker values
# in this case, there's a 17OHP value of 12240 (row 917) which needs to be removed
# can't work out how to do <710 (next highest legit value) and keep NAs too (without keep NAs, I lose lots of rows)
# let's just remove this one row manually this time...
data_biomarkers <- data_biomarkers[-917,]

# make female and male subset dataframes
female_biomarkers <- data_biomarkers[data_biomarkers$Sex.at.birth == "Female",]
male_biomarkers <- data_biomarkers[data_biomarkers$Sex.at.birth == "Male",]
NA_biomarkers <- data_biomarkers[data_biomarkers$Sex.at.birth == "Not Assigned",]

biomarkers_vs_dose_all <- pairs(data_biomarkers[, c(2,3,5,6)], pch = 19, lower.panel = NULL, main = "Biomarkers vs HCe total daily dose per BSA (all data)", na.action = na.omit)

female_biomarkers_vs_dose <- pairs(female_biomarkers[, c(2,3,5,6)], pch= 19, col = "red", lower.panel = NULL, main = "Biomarkers vs HCe total daily dose per BSA (females)")

male_biomarkers_vs_dose <- pairs(male_biomarkers[, c(2,3,5,6)], pch = 19, col = "blue", lower.panel = NULL,  main = "Biomarkers vs HCe total daily dose per BSA (males)")

NA_biomarkers_vs_dose <- pairs(NA_biomarkers[, c(2,3,5,6)], pch = 19, col = "green", lower.panel = NULL, main = "Biomarkers vs HCe total daily dose per BSA (Not Assigned)")

#
biomarkers_vs_dose <- ggpairs(data_biomarkers[, c(2,3,5,6)], pch = 19)
```



-----------
```{r : violin plots}
andro_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = Androstenedione.value, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Androstenedione concentrations") +
  geom_point(position = position_jitter(seed = 1, width = 0.2)) +
  scale_y_break(c(20,30,55,70), scale = 0.25) +
  scale_y_continuous(breaks = seq(0, 70, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")

testosterone_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Testosterone concentrations") +
  geom_point(position = position_jitter(seed = 1, width = 0.2)) +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5))

# add in age category grouping
testosterone_violin2 <- ggplot(all_data, aes(x = Sex.at.birth, y = `Total.testosterone.value`, fill = Age.category)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Testosterone concentrations") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
  scale_fill_manual(values = myColours) +
  geom_point(position = position_dodge(width = 1),
                 aes(group = Age.category)) 


# introduce age category
# only need age category for males so will need to do some powerpoint cropping
    testosterone_all_violin_2 <- ggplot(all_data, aes(x = Sex.at.birth, y = Total.testosterone.value, fill = Age.category, col = Sex.at.birth)) +
      geom_violin() +
      scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
      labs(title = "Testosterone 22-25", x = "Centre ID", y = "Total.testosterone.value") +
      theme_classic() +
      theme() +
      scale_fill_manual(values = myColours) +
      geom_point(position = position_dodge(width = 0.75),
                 aes(group = Age.category))
#

renin_violin <- ggplot(all_data, aes(x = Sex.at.birth, y = Renin.plasma.activity, fill = Sex.at.birth)) +
  geom_violin() +
  theme_classic() +
  ggtitle("Renin plasma activity") +
  geom_point(position = position_jitter(seed = 1, width = 0.2)) +
  scale_y_break(c(60, 100), scale = 0.25)

```

```{r : biomarker box plots}
# have played around with various axis breaks and y scales to get data to look as clear as possible...
## testosterone
testosterone_all <- MDBoxPlot(all_data, "Total.testosterone.value", "Sex only", "Testosterone (all data)") +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5))

# introduce age category
# only need age category for males so will need to do some powerpoint cropping
testosterone_all2 <- ggplot(all_data, aes(x = Sex.at.birth, y = Total.testosterone.value, fill = Age.category, col = Sex.at.birth)) +
  geom_boxplot(position = position_dodge2(preserve='single'),) +
  scale_y_continuous(breaks = seq(0, 30, by = 2.5)) +
  labs(title = "Total testosterone (all data)", x = "Centre ID", y = "Total.testosterone.value") +
  theme_classic() +
  theme() +
  scale_fill_manual(values = myColours) +
  geom_point(position = position_dodge(width = 0.75),
             aes(group = Age.category))
#

## renin plasma activity
renin_all <- MDBoxPlot(all_data, "Renin.plasma.activity", "Sex only", "Renin plasma activiy") +
scale_y_break(c(60, 100), scale = 0.25)

## 17OHP
OHP_all <- MDBoxPlot(all_data, "X17.OHP.value", "Sex only", "17 OHP values") +
  scale_y_continuous(trans = "log10")  +
  geom_hline(yintercept = 30, colour = "red") +
  annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=36, alpha=.5, fill='grey')

##andro
andro_all <- MDBoxPlot(all_data, "Androstenedione.value", "Sex only", "Andro values") +
  scale_y_break(c(20,30,55,70), scale = 0.1) + 
  scale_y_continuous(breaks = seq(0, 75, by = 2)) +
  geom_hline(yintercept = 8, colour = "red")
```

```{r}

```

```{r : end of script message}
print("Script complete")
```









